version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"
    networks:
      - ecommerce-enoca-network
  application:
    container_name: ecommerce-enoca
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - ecommerce-enoca-network
    depends_on:
      - "postgres"
networks:
  ecommerce-network:
    name: ecommerce-enoca-network
    driver: bridge
